import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        <Footer />
        <Toaster
          position="top-center"
          closeButton
          toastOptions={{
            style: {
              background: "#0f172a",
              color: "#fff",
              borderRadius: "12px",
              border: "1px solid #334155",
              backdropFilter: "blur(20px)",
              WebkitBackdropFilter: "blur(20px)",
            },
          }}
        />
      </body>
    </html>
  );
}
